#!/usr/bin/env bash

# Autostart.
sxhkd &
dunst &
nitrogen --restore
polybar mybar &
picom --config /home/sudozelda/.picom.conf --backend glx &

# Set decoration geometry
berryc border_width       0
berryc inner_border_width 0
berryc title_height       32
berryc top_gap            32
berryc edge_gap						10

# Set decoration colors
berryc focus_color         2E3440
berryc unfocus_color       2E3440
berryc inner_focus_color   81A1C1
berryc inner_unfocus_color 4C566A
berryc text_focus_color    2E3440
berryc text_unfocus_color  4C566A

# Other options
berryc pointer_focus "true"
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "false"
berryc set_font    "Dina-9"
