#! /bin/sh
#
###########################################################
##                                                       ##
##  ░▒█▀▀▄░█▀▀░▄▀▀▄░█░░░█░█▀▄▀█                              ##
##  ░▒█▀▀▄░▀▀▄░█▄▄█░▀▄█▄▀░█░▀░█                              ##
##  ░▒█▄▄█░▀▀▀░█░░░░░▀░▀░░▀░░▒▀                              ## 
##                                                       ##
##  My simple Bspwm config.                              ##
##  Please read documentation before editing this file!  ## 
##  Manpage bspwm                                        ##
##  https://wiki.archlinux.org/index.php/bspwm           ##
##  https://github.com/baskerville/bspwm                 ##
##                                                       ##
########################################################### 
#
export BSPWM_SCRIPTS_DIR="$HOME/.config/bspwm/scripts"
#
# -- Killing some programs after restarting bspwm.
pkill sxhkd 
pkill polybar 

# -- Autostarting some programs.
# borders &
polybar mybar &
nitrogen --restore &
xsetroot -cursor_name left_ptr &
pgrep -x sxhkd > /dev/null || sxhkd &
picom --config /home/sudozelda/.picom.conf --backend glx &

# --- Defining my modkey.
bspc config pointer_modifier mod4

# --- Defining my workspace names.
bspc monitor -d term code web chat gfx media games

# --- Bspwm Settings.
bspc config click_to_focus       button1
bspc config focus_follows_pointer true
bspc config honor_size_hints     false
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config paddingless_monocle  true
bspc config pointer_motion_interval 7ms
bspc config history_aware_focus    true
bspc config adaptative_raise true
bspc config apply_floating_atom    true

bspc config ignore_ewmh_struts false
bspc config ignore_ewmh_focus true

# Theming options.
bspc config border_width 3
bspc config normal_border_color  "#4C566A"
bspc config active_border_color  "#8FBCBB"
bspc config focused_border_color "#8FBCBB"

#This creates negative padding eaual to window gap so that gaps are shown only between windows and not on desktop edges.
bspc config window_gap 10
bspc config top_padding 42
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

# --- Window Rules.
bspc rule -a lightcord desktop='^4' follow=on state=floating state=center
bspc rule -a LibreWolf desktop='^3' follow=on
bspc rule -a Lxappearance floating=true center=true
bspc rule -a Nitrogen state=floating
bspc rule -a Lxappearance state=floating state=center
bspc rule -a Xarchiver state=floating
bspc rule -a Gnome-screenshot state=floating
bspc rule -a Gpick state=floating
bspc rule -a Gimp.bin desktop='^5' state=floating follow=on state=center 
