#! /bin/bash
#
# wm independent hotkeys
#

# terminal emulator
super + shift + Return
	st -e fish

# alt term
super + Return
	alacritty -e fish
	
# program launcher
super + p
	dmenu_run

# browser
super + control + b
      	librewolf

# editor
super + control + e
      	emacs

# nitrogen
super + control + n
      	nitrogen

# nmtui
super + control + w
      	st -e nmtui

# htop
super + control + h
      	st -e htop

# lightcord
super + control + d
      	lightcord

# pcmanfm
super + control + f
      	pcmanfm

# volume
XF86AudioRaiseVolume
	pactl set-sink-volume 0 +5% 
XF86AudioLowerVolume
	pactl set-sink-volume 0 -5%
XF86AudioMute
	pactl set-sink-mute 0 toggle

# brightness
XF86MonBrightnessUp
	brightnessctl s +3%
XF86MonBrightnessDown
	brightnessctl s 3%-

# Screenshot
Print
	gnome-screenshot -i

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

#
# bspwm hotkeys
#

# quit/restart bspwm
super + shift + {q,r}
	bspc {quit,wm -r}

super + shift + r
	$HOME/.config/2bwm/autostart.sh
	
# close and kill
super + {_,shift + }c
	bspc node -{c,k}

# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

# send the newest marked node to the newest preselected node
super + y
	bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest window
super + g
	bspc node -s biggest.window

#
# state/flags
#

# set the window state
super + {t,s,f}
	bspc node -t {tiled,floating,fullscreen}

# set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

#
# focus/swap
#

# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous window in the current desktop
super + {_,shift + }c
	bspc node -f {next,prev}.local.!hidden.window

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

#
# preselect
#

# preselect the direction
super + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

# Change window gap
ctrl + space   
    bspc config -d focused window_gap {10,15,20,25,30,35,40,45,50,55,60,65}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}
